services:
  swiss_mountains:
    image: swiss_mountains:latest
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cache:/app/cache
      - /run/media/tim/T9/mountain_cache/gifs/:/app/gifs