[package]
name = "swiss_mountains_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "swiss_mountains"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.99"
delaunator = "1.0.2"
env_logger = "0.11.8"
gif = "0.13.3"
image = "0.25.8"
kiddo = "5.2.2"
log = "0.4.28"
nalgebra = "0.33.2"
pyo3 = { version = "0.26", features = ["extension-module"] }
rayon = "1.11.0"
reqwest = { version = "0.12.23", features = [
    "blocking",
    "rustls-tls",
], default-features = false }
rusqlite = "0.37.0"
serial_test = "3.2.0"
three-d = { version = "0.18.2", features = ["headless"] }
three-d-asset = { version = "0.9.2", features = ["gif", "png"] }
tiff = "0.10.3"
tokio = { version = "1.47.1", features = ["full", "macros", "sync"] }
yuv = "0.8.6"
zip = "4.6.0"
